### ISSUE TITLE
Elección de los patrones

### ISSUE THREAD

**Issue by squella** [asleybach/ejercicio_java_figuras#1]
Antes de aplicar un abstract factory tendría que tener un factory method (KISS y YAGNI). Por otro lado el patron Chain of Responsability no veo que sea el más indicado, recuerda que siempre tienes que resolver un problema, dado un problema comun usamos un patron, aquí podríamos tener el "problema". 

Refactoriza el código usando los patrones Factory Method y el Strategy. Explica el problema que vamos a resolver con cada patron y compáralo con los que habías usado anteriormente:

Abstract factory vs Factory Method
Chain of Responsability cd Strategy

NOTA: Singleton ahora se considera una mala practica : /

**Comment by asleybach** [comment]
En primera, el problema es que tengo la necesidad de crear figuras distintas, a las cuales le debo calcular área y perímetro. De manera que se crea la clase Figura, Circulo, Cuadrado y Triangulo son subclases de Figura. se crea la clase FiguraFactory que permite que en la subclase se seleccione el objeto a crear y se calcule las medidas de área y perímetro sobrescribiendo los métodos correspondientes de la clase padre [Figura]

**Comment by asleybach** [comment]
en cuanto a la aplicación del patron de diseño de comportamiento Strategy, pues la implementación cambio por completo... se creo una clase CalculadorArea... esa clase es una interface, las clases creadas en particular para la estrategia de aplicación de la lógica necesaria para calcular la medida de área para cada figura [ solo se uso el calculo de área como ejemplo] implementa esta interface y se crea clase contexto para aplicar el calculo llamando a la clase respectiva según sea el tipo de figura.

**Comment by squella** [comment]
> En primera, el problema es que tengo la necesidad de crear figuras distintas, a las cuales le debo calcular área y perímetro. De manera que se crea la clase Figura, Circulo, Cuadrado y Triangulo son subclases de Figura. se crea la clase FiguraFactory que permite que en la subclase se seleccione el objeto a crear y se calcule las medidas de área y perímetro sobrescribiendo los métodos correspondientes de la clase padre [Figura]
Entiendo, por eso es la diferencia de abstact factory vs factory method, me gustaría que me la explicaras y despues veas cual aplica mejor a tu caso y por qué

**Comment by asleybach** [comment]
Si entendí bien, y luego de investigarlo mas a profundidad... el tema esta en que el método Factory es el adecuado para crear uno o varios objetos sin modificar el código que ya se tiene, a partir de una clase interface. El método Abstract Factory funciona si gustas crear familias de objetos o colecciones de objetos sin especificar tipo concreto pues se espera variaciones en las características de los miembros de la colección. En el caso del problema planteado... puede esperarse la creación de mas objetos correspondientes a mas figuras [ rombo, pentágono, entre otros ] a los cuales se le podrá calcular el área y el perímetro, que son características [medidas] concretas de esos posibles objetos, por lo que usar el método abstract factory corresponde una complicación innecesaria.

**Comment by squella** [comment]
Si correcto Asley
